#!/usr/bin/env python3
"""
Weekly Summary generator for Obsidian daily notes.
Reads Mon-Fri daily notes and writes a Weekly Summary note.
Can run standalone or be called by wrap_up.py on Fridays.
"""

import sys
import argparse
from datetime import datetime, timedelta
from pathlib import Path

sys.path.insert(0, str(Path(__file__).parent))
from todo_migrator import TodoMigrator
from llm_utils import call_llm


class WeeklySummary:
    def __init__(self, vault_path="Desktop/obsidian_vault", week_spec=None,
                 use_claude=False, use_sonnet=False, ollama_model=None, dry_run=False):
        self.vault_path = Path.home() / vault_path
        self.migrator = TodoMigrator(vault_path)
        self.week_spec = week_spec
        self.use_claude = use_claude
        self.use_sonnet = use_sonnet
        self.ollama_model = ollama_model
        self.dry_run = dry_run

    def get_week_range(self):
        today = datetime.now()
        spec = self.week_spec

        if spec is None or spec == 'current':
            anchor = today
        elif spec == 'last':
            anchor = today - timedelta(days=7)
        else:
            anchor = datetime.strptime(spec, '%Y-%m-%d')

        monday = anchor - timedelta(days=anchor.weekday())
        friday = monday + timedelta(days=4)
        return monday, friday

    def read_week_notes(self, monday, friday):
        notes = {}
        d = monday
        while d <= friday:
            if d.weekday() < 5:
                path = self.migrator.get_daily_note_path(d)
                if path.exists():
                    try:
                        notes[d] = path.read_text(encoding='utf-8')
                    except IOError:
                        pass
            d += timedelta(days=1)
        return notes

    def generate_summary(self, notes_by_date):
        combined = ""
        for date in sorted(notes_by_date):
            combined += f"\n\n### {date.strftime('%A, %B %d')}\n{notes_by_date[date]}"
        prompt = (
            f"Here are my daily notes from this week:\n{combined}\n\n"
            "Summarize in 5-8 sentences: main themes, key accomplishments, "
            "and items carried forward. Be concise and specific."
        )
        return call_llm(prompt, self.use_claude, self.use_sonnet, self.ollama_model, model="sonnet")

    def write_summary(self, monday, summary_text, model_label):
        filename = f"Weekly Summary {monday.strftime('%Y-%m-%d')}.md"
        output_path = self.vault_path / "Daily notes" / filename

        if self.dry_run:
            print(f"  [dry-run] Would write Daily notes/{filename}")
            return

        if output_path.exists():
            print(f"  Weekly summary already exists at {filename}, skipping")
            return

        content = (
            f"# Weekly Summary: Week of {monday.strftime('%B %d, %Y')}\n\n"
            f"{summary_text}\n\n"
            f"*Generated by: {model_label} on {datetime.now().strftime('%A %B %d')}*\n"
        )
        output_path.write_text(content, encoding='utf-8')
        print(f"  ✅ Written to Daily notes/{filename}")

    def run(self):
        monday, friday = self.get_week_range()
        print(f"📅 Weekly Summary: {monday.strftime('%b %d')}–{friday.strftime('%b %d, %Y')}")

        notes = self.read_week_notes(monday, friday)
        if not notes:
            print("  No notes found for this week")
            return False

        print(f"  Found {len(notes)} notes")

        if self.dry_run:
            print(f"  [dry-run] Would write Weekly Summary {monday.strftime('%Y-%m-%d')}.md")
            return True

        print("  Generating summary...")
        summary, model = self.generate_summary(notes)
        self.write_summary(monday, summary, model)
        return True


def main():
    parser = argparse.ArgumentParser(
        description="Generate a weekly summary from Obsidian daily notes",
        epilog="""
Examples:
  python3 weekly_summary.py                   # Summarize current week
  python3 weekly_summary.py --week last       # Summarize last week
  python3 weekly_summary.py --week 2026-04-28 # Summarize week containing this date
  python3 weekly_summary.py --dry-run         # Preview without writing
        """
    )
    parser.add_argument("--vault-path", default="Desktop/obsidian_vault",
                        help="Path to Obsidian vault (relative to home)")
    parser.add_argument("--week", dest="week_spec",
                        help="Week to summarize: current (default), last, or YYYY-MM-DD")
    parser.add_argument("--use-claude", action="store_true",
                        help="Force Claude Haiku instead of ollama")
    parser.add_argument("--use-sonnet", action="store_true",
                        help="Force Claude Sonnet")
    parser.add_argument("--ollama-model", help="Pin a specific ollama model")
    parser.add_argument("--dry-run", action="store_true",
                        help="Show plan without writing files")
    args = parser.parse_args()

    try:
        ws = WeeklySummary(
            vault_path=args.vault_path,
            week_spec=args.week_spec,
            use_claude=args.use_claude,
            use_sonnet=args.use_sonnet,
            ollama_model=args.ollama_model,
            dry_run=args.dry_run,
        )
        success = ws.run()
        sys.exit(0 if success else 1)
    except KeyboardInterrupt:
        print("\n❌ Interrupted")
        sys.exit(1)
    except Exception as e:
        print(f"❌ Unexpected error: {e}")
        sys.exit(1)


if __name__ == "__main__":
    main()
